project:
  type: book
  output-dir: _book
  post-render: quarto render --profile slides

number-depth: 1

book:
  reader-mode: false
  title: "Math√©matiques HEI"
  chapters:
    - index.qmd
    - part: "Analyse 3"
      chapters:
        - an3/index.qmd
        - an3/251104/index.qmd
        - an3/260108/index.qmd
format:
  live-html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
